# Generated by Django 4.2.11 on 2024-04-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('room_number', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(choices=[('ela', 'ela'), ('math', 'math'), ('science', 'science'), ('health', 'health')], max_length=200, null=True)),
            ],
        ),
    ]
